FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm ci --omit=dev

COPY prisma ./prisma
RUN npx prisma generate

COPY src ./src

EXPOSE 3000

# Aplica migrações e sobe o servidor
CMD ["sh", "-c", "npx prisma db push --skip-generate && node src/servidor.js"]
